### ISSUE TITLE
关于BTCV数据集的预处理

### ISSUE THREAD

**Issue by QiyuanY** [lin-tianyu/Stable-Diffusion-Seg#26]
请问这个数据集是如何获得test_vol这个dataset类的数据的，在经过nii2format处理rawdata后，只能得到train和test两个数据集，训练代码中要求有包含png图片的test_vol文件夹

**Comment by QiyuanY** [comment]
有个地方打错了，test_vol应该是如下的要求
        if mode == "test_vol":
            self.data_paths = glob.glob(os.path.join(self.data_root, "img*"))#[:1]
显然应该是img开头的文件，但是处理过程并没有获得这样的文件

**Comment by lin-tianyu** [comment]
你好，凑巧昨天也有人问了类似的问题，这里是我的回复：https://github.com/lin-tianyu/Stable-Diffusion-Seg/issues/24#issuecomment-2533650347

简单来说，预处理代码中并没有包含test_vol的数据这一步，因为这部分数据不需要任何预处理，只需要简单讲nfiti数据粘贴到对应的文件夹下就可以了，因此没有在代码中展现出来。测试集中所用的nfiti数据在nii2format.py中有[记录](https://github.com/lin-tianyu/Stable-Diffusion-Seg/blob/838874893b588bf8b5c6e371d7976cb0a30b876d/data/synapse/nii2format.py#L20)。

**Comment by QiyuanY** [comment]
好的感谢
