### ISSUE TITLE
Multi-classification data preprocessing

### ISSUE THREAD

**Issue by GOZIHUATANEJO** [lin-tianyu/Stable-Diffusion-Seg#28]
Greetings from lin-tianyu:
Thank you very much for your excellent work and sharing.
I am using your code to process my semantic segmentation task with modifications based on synapse.py and I have two questions:
The first is at line 150
example[“image”] = image # range from -1 to 1, np.float32
The comment says range from -1 to 1, np.float32, but it doesn't actually do that.
The second question is on line 142: in the case where num_classes is 9
            if class_id ! = 0.
                segmentation = (segmentation == class_id) # for multi, get a random class (existed) except 0
            else: segmentation = (segmentation == class_id)
                segmentation = (segmentation ! = class_id) # (empty slice) or (not empty slice & class_id==0)
This logic takes the multi-categorized segmentation and randomly selects one class as the foreground and the rest as the background, eventually changing the range to [-1, 1] with the following statement:
Since my task is to categorize nine categories, would randomly selecting a category and binarizing it result in the loss of information from the other categories? 

Very much looking forward to your reply.

**Comment by lin-tianyu** [comment]
Hi,

For your first question, the comment is to **remind** us that the `image` here should be range from [-1, 1] in np.float32 type. The actual preprocess code for this is elsewhere: [Dataset Settings](https://github.com/lin-tianyu/Stable-Diffusion-Seg?tab=readme-ov-file#-dataset-settings) (`synapse.py` corresponds to `BTCV` dataset).

**Comment by lin-tianyu** [comment]
For your second question, like what I said in another issue https://github.com/lin-tianyu/Stable-Diffusion-Seg/issues/16#issuecomment-2357482258, the multi-class segmentation feature is not optimal and still developing.
The randomly selected one-class method for each training iteration is the best-performing method so far and will be further improved in the future.

So yes, the randomly selected one-class method would bring deduction to the imbalanced class (for example, pancreas compared to lung). Personally, I think having the model sufficiently trained with a large dataset would alleviate this issue. But there has to be another way that can better expand SDSeg to multi-class segmentation. 

Good luck on your project, and I am happy to corporate if you have any ideas!

**Comment by GOZIHUATANEJO** [comment]
Thank you very much for your reply, it was very enlightening!
