### ISSUE TITLE
Bug in downloading pre-trained wights of the denoising UNet

### ISSUE THREAD

**Issue by ishitajain21** [lin-tianyu/Stable-Diffusion-Seg#8]
The script has a small bug, that it cannot find the correct directory, fixed here: 

#!/bin/bash
wget -O models/ldm/lsun_churches256/lsun_churches-256.zip https://ommer-lab.com/files/latent-diffusion/lsun_churches.zip

cd models/ldm/lsun_churches256
unzip -o lsun_churches-256.zip

cd ../..

**Comment by lin-tianyu** [comment]
Hi, @ishitajain21, thanks for your correction! 

PS: If you want to be a contributor to our repo, you can submit a pull request. If not, I will modify it myself and close this issue in ONE day. Thanks!

**Comment by ishitajain21** [comment]
Sounds good I can open a PR!
